/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.serializer;

import com.google.inject.Inject;
import fr.n7.petrinet.services.PetriNetGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import petrinet.Arc;
import petrinet.PetriNet;
import petrinet.PetriNetPackage;
import petrinet.Place;
import petrinet.Transition;

@SuppressWarnings("all")
public class PetriNetSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private PetriNetGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PetriNetPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PetriNetPackage.ARC:
				sequence_Arc(context, (Arc) semanticObject); 
				return; 
			case PetriNetPackage.PETRI_NET:
				sequence_PetriNet(context, (PetriNet) semanticObject); 
				return; 
			case PetriNetPackage.PLACE:
				sequence_Place(context, (Place) semanticObject); 
				return; 
			case PetriNetPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Arc returns Arc
	 *
	 * Constraint:
	 *     (kind=ArcKind? source=[Node|EString] target=[Node|EString] weight=EInt?)
	 * </pre>
	 */
	protected void sequence_Arc(ISerializationContext context, Arc semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PetriNet returns PetriNet
	 *
	 * Constraint:
	 *     (name=EString (petrielement+=Node | petrielement+=Arc)*)
	 * </pre>
	 */
	protected void sequence_PetriNet(ISerializationContext context, PetriNet semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Place
	 *     Place returns Place
	 *
	 * Constraint:
	 *     (name=EString marking=EInt?)
	 * </pre>
	 */
	protected void sequence_Place(ISerializationContext context, Place semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Transition
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PetriNetPackage.Literals.NODE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PetriNetPackage.Literals.NODE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTransitionAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
