/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PetriNetAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/n7/petrinet/parser/antlr/internal/InternalPetriNet.tokens");
	}
}
