/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.parser.antlr;

import com.google.inject.Inject;
import fr.n7.petrinet.parser.antlr.internal.InternalPetriNetParser;
import fr.n7.petrinet.services.PetriNetGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PetriNetParser extends AbstractAntlrParser {

	@Inject
	private PetriNetGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPetriNetParser createParser(XtextTokenStream stream) {
		return new InternalPetriNetParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PetriNet";
	}

	public PetriNetGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetriNetGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
