/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPetriNetScopeProvider extends DelegatingScopeProvider {
}
