/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ui.tests;

import com.google.inject.Injector;
import fr.n7.petrinet.ui.internal.PetrinetActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PetriNetUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PetrinetActivator.getInstance().getInjector("fr.n7.petrinet.PetriNet");
	}

}
