/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PetriNetStandaloneSetup extends PetriNetStandaloneSetupGenerated {

	public static void doSetup() {
		new PetriNetStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
