/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PetriNetRuntimeModule extends AbstractPetriNetRuntimeModule {
}
