/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.petrinet.PetriNetRuntimeModule;
import fr.n7.petrinet.PetriNetStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PetriNetIdeSetup extends PetriNetStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PetriNetRuntimeModule(), new PetriNetIdeModule()));
	}
	
}
