/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ui;

import com.google.inject.Injector;
import fr.n7.petrinet.ui.internal.PetrinetActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PetriNetExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PetrinetActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PetrinetActivator activator = PetrinetActivator.getInstance();
		return activator != null ? activator.getInjector(PetrinetActivator.FR_N7_PETRINET_PETRINET) : null;
	}

}
