/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PetriNetUiModule extends AbstractPetriNetUiModule {

	public PetriNetUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
