/**
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.formatting2;

import com.google.inject.Inject;
import fr.n7.petrinet.services.PetriNetGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import petrinet.PetriElement;
import petrinet.PetriNet;

@SuppressWarnings("all")
public class PetriNetFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private PetriNetGrammarAccess _petriNetGrammarAccess;

  protected void _format(final PetriNet petriNet, @Extension final IFormattableDocument document) {
    EList<PetriElement> _petrielement = petriNet.getPetrielement();
    for (final PetriElement petriElement : _petrielement) {
      document.<PetriElement>format(petriElement);
    }
  }

  @XbaseGenerated
  public void format(final Object petriNet, final IFormattableDocument document) {
    if (petriNet instanceof XtextResource) {
      _format((XtextResource)petriNet, document);
      return;
    } else if (petriNet instanceof PetriNet) {
      _format((PetriNet)petriNet, document);
      return;
    } else if (petriNet instanceof EObject) {
      _format((EObject)petriNet, document);
      return;
    } else if (petriNet == null) {
      _format((Void)null, document);
      return;
    } else if (petriNet != null) {
      _format(petriNet, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(petriNet, document).toString());
    }
  }
}
