/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.n7.petrinet.ide.contentassist.antlr.internal.InternalPetriNetParser;
import fr.n7.petrinet.services.PetriNetGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PetriNetParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PetriNetGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PetriNetGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPetriNetAccess().getAlternatives_3(), "rule__PetriNet__Alternatives_3");
			builder.put(grammarAccess.getNodeAccess().getAlternatives(), "rule__Node__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getArcKindAccess().getAlternatives(), "rule__ArcKind__Alternatives");
			builder.put(grammarAccess.getPetriNetAccess().getGroup(), "rule__PetriNet__Group__0");
			builder.put(grammarAccess.getPlaceAccess().getGroup(), "rule__Place__Group__0");
			builder.put(grammarAccess.getPlaceAccess().getGroup_2(), "rule__Place__Group_2__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getArcAccess().getGroup(), "rule__Arc__Group__0");
			builder.put(grammarAccess.getArcAccess().getGroup_6(), "rule__Arc__Group_6__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getPetriNetAccess().getNameAssignment_1(), "rule__PetriNet__NameAssignment_1");
			builder.put(grammarAccess.getPetriNetAccess().getPetrielementAssignment_3_0(), "rule__PetriNet__PetrielementAssignment_3_0");
			builder.put(grammarAccess.getPetriNetAccess().getPetrielementAssignment_3_1(), "rule__PetriNet__PetrielementAssignment_3_1");
			builder.put(grammarAccess.getPlaceAccess().getNameAssignment_1(), "rule__Place__NameAssignment_1");
			builder.put(grammarAccess.getPlaceAccess().getMarkingAssignment_2_1(), "rule__Place__MarkingAssignment_2_1");
			builder.put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
			builder.put(grammarAccess.getArcAccess().getKindAssignment_1(), "rule__Arc__KindAssignment_1");
			builder.put(grammarAccess.getArcAccess().getSourceAssignment_3(), "rule__Arc__SourceAssignment_3");
			builder.put(grammarAccess.getArcAccess().getTargetAssignment_5(), "rule__Arc__TargetAssignment_5");
			builder.put(grammarAccess.getArcAccess().getWeightAssignment_6_1(), "rule__Arc__WeightAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PetriNetGrammarAccess grammarAccess;

	@Override
	protected InternalPetriNetParser createParser() {
		InternalPetriNetParser result = new InternalPetriNetParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PetriNetGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetriNetGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
