/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class PetriNetOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
