/*
 * generated by Xtext 2.41.0
 */
package fr.n7.petrinet.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PetriNetGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PetriNetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.PetriNet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPetrinetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cPetrielementAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cPetrielementNodeParserRuleCall_3_0_0 = (RuleCall)cPetrielementAssignment_3_0.eContents().get(0);
		private final Assignment cPetrielementAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cPetrielementArcParserRuleCall_3_1_0 = (RuleCall)cPetrielementAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//// --- 1. RÈGLE RACINE (Doit impérativement être la première !) ---
		//// ATTENTION: Vérifiez si les mots "nodes" et "arcs" correspondent bien
		//// aux noms de vos relations de contenance dans votre fichier PetriNet.ecore
		//PetriNet returns PetriNet:
		//    'petrinet' name=EString '{'
		//        (petrielement+=Node | petrielement+=Arc)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'petrinet' name=EString '{'
		//    (petrielement+=Node | petrielement+=Arc)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'petrinet'
		public Keyword getPetrinetKeyword_0() { return cPetrinetKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(petrielement+=Node | petrielement+=Arc)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//petrielement+=Node
		public Assignment getPetrielementAssignment_3_0() { return cPetrielementAssignment_3_0; }
		
		//Node
		public RuleCall getPetrielementNodeParserRuleCall_3_0_0() { return cPetrielementNodeParserRuleCall_3_0_0; }
		
		//petrielement+=Arc
		public Assignment getPetrielementAssignment_3_1() { return cPetrielementAssignment_3_1; }
		
		//Arc
		public RuleCall getPetrielementArcParserRuleCall_3_1_0() { return cPetrielementArcParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.Node");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPlaceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// --- 2. LES NOEUDS ---
		//Node returns Node:
		//    Place | Transition;
		@Override public ParserRule getRule() { return rule; }
		
		//Place | Transition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Place
		public RuleCall getPlaceParserRuleCall_0() { return cPlaceParserRuleCall_0; }
		
		//Transition
		public RuleCall getTransitionParserRuleCall_1() { return cTransitionParserRuleCall_1; }
	}
	public class PlaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.Place");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMarkingKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMarkingAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMarkingEIntParserRuleCall_2_1_0 = (RuleCall)cMarkingAssignment_2_1.eContents().get(0);
		
		//Place returns Place:
		//    'place' name=EString ('marking' marking=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'place' name=EString ('marking' marking=EInt)?
		public Group getGroup() { return cGroup; }
		
		//'place'
		public Keyword getPlaceKeyword_0() { return cPlaceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('marking' marking=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'marking'
		public Keyword getMarkingKeyword_2_0() { return cMarkingKeyword_2_0; }
		
		//marking=EInt
		public Assignment getMarkingAssignment_2_1() { return cMarkingAssignment_2_1; }
		
		//EInt
		public RuleCall getMarkingEIntParserRuleCall_2_1_0() { return cMarkingEIntParserRuleCall_2_1_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Transition returns Transition:
		//    'transition' name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'transition' name=EString
		public Group getGroup() { return cGroup; }
		
		//'transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class ArcElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.Arc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArcKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cKindAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cKindArcKindEnumRuleCall_1_0 = (RuleCall)cKindAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSourceNodeCrossReference_3_0 = (CrossReference)cSourceAssignment_3.eContents().get(0);
		private final RuleCall cSourceNodeEStringParserRuleCall_3_0_1 = (RuleCall)cSourceNodeCrossReference_3_0.eContents().get(1);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTargetNodeCrossReference_5_0 = (CrossReference)cTargetAssignment_5.eContents().get(0);
		private final RuleCall cTargetNodeEStringParserRuleCall_5_0_1 = (RuleCall)cTargetNodeCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWeightKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWeightAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cWeightEIntParserRuleCall_6_1_0 = (RuleCall)cWeightAssignment_6_1.eContents().get(0);
		
		//// --- 3. LES ARCS ---
		//Arc returns Arc:
		//    'arc' (kind=ArcKind)? 'from' source=[Node|EString] 'to' target=[Node|EString] ('weight' weight=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'arc' (kind=ArcKind)? 'from' source=[Node|EString] 'to' target=[Node|EString] ('weight' weight=EInt)?
		public Group getGroup() { return cGroup; }
		
		//'arc'
		public Keyword getArcKeyword_0() { return cArcKeyword_0; }
		
		//(kind=ArcKind)?
		public Assignment getKindAssignment_1() { return cKindAssignment_1; }
		
		//ArcKind
		public RuleCall getKindArcKindEnumRuleCall_1_0() { return cKindArcKindEnumRuleCall_1_0; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//source=[Node|EString]
		public Assignment getSourceAssignment_3() { return cSourceAssignment_3; }
		
		//[Node|EString]
		public CrossReference getSourceNodeCrossReference_3_0() { return cSourceNodeCrossReference_3_0; }
		
		//EString
		public RuleCall getSourceNodeEStringParserRuleCall_3_0_1() { return cSourceNodeEStringParserRuleCall_3_0_1; }
		
		//'to'
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//target=[Node|EString]
		public Assignment getTargetAssignment_5() { return cTargetAssignment_5; }
		
		//[Node|EString]
		public CrossReference getTargetNodeCrossReference_5_0() { return cTargetNodeCrossReference_5_0; }
		
		//EString
		public RuleCall getTargetNodeEStringParserRuleCall_5_0_1() { return cTargetNodeEStringParserRuleCall_5_0_1; }
		
		//('weight' weight=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'weight'
		public Keyword getWeightKeyword_6_0() { return cWeightKeyword_6_0; }
		
		//weight=EInt
		public Assignment getWeightAssignment_6_1() { return cWeightAssignment_6_1; }
		
		//EInt
		public RuleCall getWeightEIntParserRuleCall_6_1_0() { return cWeightEIntParserRuleCall_6_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//// --- 4. RÈGLES DE BASE ---
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class ArcKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.petrinet.PetriNet.ArcKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNormalEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNormalNormalKeyword_0_0 = (Keyword)cNormalEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRead_arcEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRead_arcRead_arcKeyword_1_0 = (Keyword)cRead_arcEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum ArcKind returns ArcKind:
		//    normal = 'normal' | read_arc = 'read_arc';
		public EnumRule getRule() { return rule; }
		
		//normal = 'normal' | read_arc = 'read_arc'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//normal = 'normal'
		public EnumLiteralDeclaration getNormalEnumLiteralDeclaration_0() { return cNormalEnumLiteralDeclaration_0; }
		
		//'normal'
		public Keyword getNormalNormalKeyword_0_0() { return cNormalNormalKeyword_0_0; }
		
		//read_arc = 'read_arc'
		public EnumLiteralDeclaration getRead_arcEnumLiteralDeclaration_1() { return cRead_arcEnumLiteralDeclaration_1; }
		
		//'read_arc'
		public Keyword getRead_arcRead_arcKeyword_1_0() { return cRead_arcRead_arcKeyword_1_0; }
	}
	
	private final PetriNetElements pPetriNet;
	private final NodeElements pNode;
	private final PlaceElements pPlace;
	private final TransitionElements pTransition;
	private final ArcElements pArc;
	private final EIntElements pEInt;
	private final EStringElements pEString;
	private final ArcKindElements eArcKind;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PetriNetGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPetriNet = new PetriNetElements();
		this.pNode = new NodeElements();
		this.pPlace = new PlaceElements();
		this.pTransition = new TransitionElements();
		this.pArc = new ArcElements();
		this.pEInt = new EIntElements();
		this.pEString = new EStringElements();
		this.eArcKind = new ArcKindElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.petrinet.PetriNet".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// --- 1. RÈGLE RACINE (Doit impérativement être la première !) ---
	//// ATTENTION: Vérifiez si les mots "nodes" et "arcs" correspondent bien
	//// aux noms de vos relations de contenance dans votre fichier PetriNet.ecore
	//PetriNet returns PetriNet:
	//    'petrinet' name=EString '{'
	//        (petrielement+=Node | petrielement+=Arc)*
	//    '}';
	public PetriNetElements getPetriNetAccess() {
		return pPetriNet;
	}
	
	public ParserRule getPetriNetRule() {
		return getPetriNetAccess().getRule();
	}
	
	//// --- 2. LES NOEUDS ---
	//Node returns Node:
	//    Place | Transition;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//Place returns Place:
	//    'place' name=EString ('marking' marking=EInt)?;
	public PlaceElements getPlaceAccess() {
		return pPlace;
	}
	
	public ParserRule getPlaceRule() {
		return getPlaceAccess().getRule();
	}
	
	//Transition returns Transition:
	//    'transition' name=EString;
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//// --- 3. LES ARCS ---
	//Arc returns Arc:
	//    'arc' (kind=ArcKind)? 'from' source=[Node|EString] 'to' target=[Node|EString] ('weight' weight=EInt)?;
	public ArcElements getArcAccess() {
		return pArc;
	}
	
	public ParserRule getArcRule() {
		return getArcAccess().getRule();
	}
	
	//// --- 4. RÈGLES DE BASE ---
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum ArcKind returns ArcKind:
	//    normal = 'normal' | read_arc = 'read_arc';
	public ArcKindElements getArcKindAccess() {
		return eArcKind;
	}
	
	public EnumRule getArcKindRule() {
		return getArcKindAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
